"""add email

Revision ID: 1b07847d06ad
Revises: dd9517808298
Create Date: 2020-11-05 17:28:21.921954

"""

# revision identifiers, used by Alembic.
revision = '1b07847d06ad'
down_revision = 'dd9517808298'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
