"""

Revision ID: 2e3b3ca8a665
Revises: 9f85248eab3f
Create Date: 2020-11-11 13:50:01.017085

"""

# revision identifiers, used by Alembic.
revision = '2e3b3ca8a665'
down_revision = '9f85248eab3f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
