"""

Revision ID: 50df99d0df73
Revises: ffa69ee071e2
Create Date: 2020-11-09 12:39:02.930059

"""

# revision identifiers, used by Alembic.
revision = '50df99d0df73'
down_revision = 'ffa69ee071e2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
