"""

Revision ID: 66214cdd3ae6
Revises: 50df99d0df73
Create Date: 2020-11-11 12:10:48.891727

"""

# revision identifiers, used by Alembic.
revision = '66214cdd3ae6'
down_revision = '50df99d0df73'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
