"""add confirmed

Revision ID: 807ee92d745f
Revises: cd6065369fcb
Create Date: 2020-11-06 16:16:08.333308

"""

# revision identifiers, used by Alembic.
revision = '807ee92d745f'
down_revision = 'cd6065369fcb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
