"""add user manager

Revision ID: 839629e0b17b
Revises: ce002b707c9b
Create Date: 2020-11-07 13:14:31.358778

"""

# revision identifiers, used by Alembic.
revision = '839629e0b17b'
down_revision = 'ce002b707c9b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
