"""

Revision ID: 8596a85080fe
Revises: 200ae97fd6c5
Create Date: 2020-11-13 17:53:27.341337

"""

# revision identifiers, used by Alembic.
revision = '8596a85080fe'
down_revision = '200ae97fd6c5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
