"""add email

Revision ID: cd6065369fcb
Revises: 1b07847d06ad
Create Date: 2020-11-05 17:35:04.161138

"""

# revision identifiers, used by Alembic.
revision = 'cd6065369fcb'
down_revision = '1b07847d06ad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
