"""add user manager

Revision ID: ce002b707c9b
Revises: 5ea24046a879
Create Date: 2020-11-07 13:09:39.000246

"""

# revision identifiers, used by Alembic.
revision = 'ce002b707c9b'
down_revision = '5ea24046a879'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
